=== OpenGovLD/popolo-spec/schemas/organization.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "http://popoloproject.com/schemas/organization.json#",
  "title": "Organization",
  "description": "A group with a common purpose or reason for existence that goes beyond the set of people belonging to it",
  "type": "object",
  "properties": {
    "_id": {
      "description": "The organization's unique identifier",
      "type": "string",
      "required": true
    },
    "name": {
      "description": "A primary name, e.g. a legally recognized name",
      "type": "string",
      "required": true
    },
    "other_names": {
      "description": "Alternate or former names",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "An alternate or former name",
            "type": "string",
            "required": true
          },
          "start_date": {
            "description": "The date on which the name was adopted",
            "type": "string",
            "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
          },
          "end_date": {
            "description": "The date on which the name was abandoned",
            "type": "string",
            "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
          }
        }
      }
    },
    "identifiers": {
      "description": "Issued identifiers",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "identifier": {
            "description": "An issued identifier, e.g. a DUNS number",
            "type": "string",
            "required": true
          },
          "scheme": {
            "description": "An identifier scheme, e.g. DUNS",
            "type": "string"
          }
        }
      }
    },
    "classifications": {
      "description": "Organization categories",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "classification": {
            "description": "An organizational category, e.g. charity, committee, etc.",
            "type": "string",
            "required": true
          }
        }
      }
    },
    "parent_id": {
      "description": "An organization that contains this organization",
      "type": "string"
    },
    "founding_date": {
      "description": "A date of founding",
      "type": "string",
      "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
    },
    "dissolution_date": {
      "description": "A date of dissolution",
      "type": "string",
      "pattern": "^[0-9]{4}(-[0-9]{2}){0,2}$"
    }
  }
}

=== OpenGovLD/popolo-spec/examples/organization.json
{
  "_id": "27cc67093475061e3d95369d",
  "name": "ABC, Inc.",
  "other_names": [
    {
      "name": "Bob's Diner",
      "start_date": "1950-01-01",
      "end_date": "1954-12-31"
    },
    {
      "name": "Joe's Diner",
      "start_date": "1955-01-01"
    },
    {
      "name": "Famous Joe's"
    }
  ],
  "identifiers": [
    {
      "identifier": "123456789",
      "scheme": "DUNS"
    },
    {
      "identifier": "US0123456789",
      "scheme": "ISIN"
    }
  ],
  "classifications": [
    {
      "classification": "Corporation"
    },
    {
      "classification": "Fast-food chain"
    }
  ],
  "parent_id": "17cc67093475061e3d95369d",
  "founding_date": "1950-01-01",
  "dissolution_date": "2000-01-01"
}
