=== OpenGovLD/popolo-spec/schemas/post.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "id": "http://popoloproject.com/schemas/post.json#",
  "title": "Post",
  "description": "A position that exists independent of the person holding it",
  "type": "object",
  "properties": {
    "id": {
      "description": "The post's unique identifier",
      "type": ["string", "null"]
    },
    "label": {
      "description": "A label describing the post",
      "type": "string",
      "required": true
    },
    "role": {
      "description": "The role that the holder of the post fulfills",
      "type": "string",
      "required": true
    },
    "person_id": {
      "description": "The ID of the person who holds the post",
      "type": ["string", "null"]
    },
    "organization_id": {
      "description": "The ID of the organization in which the post is held",
      "type": ["string", "null"]
    },
    "links": {
      "description": "URLs for documents about the person",
      "type": "array",
      "items": {
        "$ref": "http://popoloproject.com/schemas/link.json#"
      }
    },
    "contact_details": {
      "description": "Means of contacting the person who holds the post",
      "type": "array",
      "items": {
        "$ref": "http://popoloproject.com/schemas/contact_detail.json#"
      }
    }
  }
}

=== OpenGovLD/popolo-spec/examples/post.json
{
  "id": "abc-inc-chef",
  "label": "Chef at Joe's Diner",
  "person_id": "john-q-public",
  "organization_id": "abc-inc",
  "role": "Chef",
  "contact_details": [
    {
      "label": "Take-out and delivery",
      "type": "tollfree",
      "value": "+1-800-555-0199",
      "note": "12pm to midnight"
    }
  ],
  "links": [
    {
      "url": "http://example.com/abc-inc/staff",
      "note": "ABC, Inc. staff page"
    }
  ]
}
